Lesson 4 3
CodergirlVS/intro-to-programming-eclipse pull request #8
Opened 2021-06-08 01:45 UTC by CodergirlVS

2021-06-08 19:33 UTC, jppianta requested changes
I know it seems a lot, but are a lot of tinny things. I am only picky because it is good

2021-06-08 19:33 UTC, jppianta commented on Final-Project/js/index.js
> +  li.innerHTML = "";
It is not recommended to use `innerHTML`, it is considered unsafe. It is better to control the Node tree using functions like `removeChild`

2021-06-08 19:33 UTC, jppianta commented on Final-Project/js/index.js
> +  e.target.removeEventListener("click", editFunction);
Since you've already deleted all elements inside the `li`, this `e.target` is not in the tree anymore, so no need to change anything about it

2021-06-08 19:33 UTC, jppianta commented on Final-Project/js/index.js
> +  return  `<a href = "mailto:${email}">${fullName}</a><span> wrote: ${message}</span>`;
Same thing about the `innerHTML`

2021-06-08 19:33 UTC, jppianta commented on Final-Project/js/index.js
> +  console.log(fullName, email, message);
It is a good practice not to leave `console.log` on the code

2021-06-08 19:33 UTC, jppianta commented on Final-Project/styles.css
>      position: initial;
No need for this `position: initial` on the body and set `margin: 0` so that the colors you use inside the sections and on the header fill like not filled

2021-06-08 19:33 UTC, jppianta commented on Final-Project/styles.css
> +    transition: all .025s;
I like the animation, but try without the 360, scaling maybe 1.1 and taking 0.125 instead of .025. It gets a lit more smooth

2021-06-08 19:33 UTC, jppianta commented on Final-Project/js/index.js
> +    event.target.textContent = event.target.textContent.toUpperCase();
Be careful with the uppercase here, because the font gets bigger and moves the rest of the menu

2021-06-08 19:33 UTC, jppianta commented on Final-Project/styles.css
> +    background-color: #cf89bc;
This is for all of your sections, but try to add a `padding`, it will look nice

2021-06-08 19:33 UTC, jppianta commented on Final-Project/styles.css
> +    padding: 5px 5px 5px 10px;
This is nice, just make sure it fits with the padding of the other elements below

2021-06-09 00:54 UTC, CodergirlVS commented on Final-Project/js/index.js
> +  li.innerHTML = "";
Thanks for your feedback. If we don't use innerHTML to set the message then what can be used which will take the HTML Tags? Also if I remove the li.removeChild() then it takes away the whole li including the buttons. I only want it to remove the HTML content.
Thanks

2021-06-09 00:55 UTC, CodergirlVS commented on Final-Project/js/index.js
> +  e.target.removeEventListener("click", editFunction);
True. Thanks. I will take it off. But we still need e.target for saveFunction.

2021-06-09 03:03 UTC, jppianta commented on Final-Project/js/index.js
> +  li.innerHTML = "";
Not to set the message, I mean not use `innerHTML` to remove the children of li

2021-06-09 07:19 UTC, CodergirlVS commented on Final-Project/js/index.js
> +  return  `<a href = "mailto:${email}">${fullName}</a><span> wrote: ${message}</span>`;
I dint get this part. And how to remove only the text from the li and not the buttons?

2021-06-09 07:21 UTC, CodergirlVS commented on Final-Project/js/index.js
> +  li.innerHTML = "";
If I do ul.removeChild(li); then the moment I click Edit button it will delete the whole item
I even tried li.remove() and it all does the same.
In above function the input values replace the older values and the same variables are storing the new info. So if I remove name or email variable then it will delete the input.value,
What is the code to remove HTML without using innerHTML =""

2021-06-10 07:25 UTC, merged

2021-06-30 19:48 UTC, rtesagg84 reviewed
All your code look's cool! just   remove the added spacing .

2021-06-30 19:48 UTC, rtesagg84 commented on Final-Project/index.html
> +                    <div></div>
remove unwanted code!

2021-06-30 19:48 UTC, rtesagg84 commented on Final-Project/js/index.js
> +
Remove  spacing!

2021-06-30 19:48 UTC, rtesagg84 commented on Final-Project/js/index.js
> +
same here!

2021-06-30 19:48 UTC, rtesagg84 commented on Final-Project/js/index.js
> +
same here!

2021-06-30 19:48 UTC, rtesagg84 commented on Final-Project/js/index.js
> +
same here

2021-06-30 19:48 UTC, rtesagg84 commented on Final-Project/index.html
>              <!-- <small>&copy; 2021 Vaidehi's Portfolio</small>    -->
It is better to have the header and footer the same color but it is totally up to your choose!

2021-06-30 20:54 UTC, CodergirlVS commented
Hi,

Thank You! The spacing is the default formatting on VS code. Is there any
particular formatting you need/recommend? And how I can change it?

Thanks
Regards
Vaidehi Sapre.

On Wed, Jun 30, 2021, 12:49 PM Aster Ghebreyesus ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> All your code look's cool! just remove the added spacing .
> ------------------------------
>
> In Final-Project/index.html
> <https://github.com/CodergirlVS/intro-to-programming-eclipse/pull/8#discussion_r661759201>
> :
>
> > @@ -48,6 +50,7 @@ <h1>Experience!</h1>
>                      of my past experiences:</p>
>                  <h3> WNS Global Services, Mumbai-India,  Sr. Analyst</h3>
>                  <h4>September 2008 - September 2010</h4>
> +                    <div></div>
>
> remove unwanted code!
> ------------------------------
>
> In Final-Project/js/index.js
> <https://github.com/CodergirlVS/intro-to-programming-eclipse/pull/8#discussion_r661761684>
> :
>
> > +function createRemoveButton() {
> +  const removeButton = document.createElement("button");
> +  removeButton.textContent = "Remove";
> +  removeButton.type = "button";
> +  removeButton.addEventListener("click", (event) => {
> +    const entry = event.target.parentNode;
> +    entry.remove();
> +    verifyingEmptyMesaages();
> +  });
> +  return removeButton;
> +}
> +
> +function formLiText(fullName, email, message) {
> +  return  `<a href = "mailto:${email}">${fullName}</a><span> wrote: ${message}</span>`;
> +}
> +
>
> Remove spacing!
> ------------------------------
>
> In Final-Project/js/index.js
> <https://github.com/CodergirlVS/intro-to-programming-eclipse/pull/8#discussion_r661761958>
> :
>
> > +  return removeButton;
> +}
> +
> +function formLiText(fullName, email, message) {
> +  return  `<a href = "mailto:${email}">${fullName}</a><span> wrote: ${message}</span>`;
> +}
> +
> +// creating Li
> +function createLi (fullName, email, message) {
> +  const newLi = document.createElement("li");
> +  return populateLi(newLi, fullName, email, message);
> +}
> +
> +function populateLi(liNode, fullName, email, message) {
> +  liNode.innerHTML = formLiText(fullName, email, message);
> +
>
> same here!
> ------------------------------
>
> In Final-Project/js/index.js
> <https://github.com/CodergirlVS/intro-to-programming-eclipse/pull/8#discussion_r661762110>
> :
>
> > +
> +// creating Li
> +function createLi (fullName, email, message) {
> +  const newLi = document.createElement("li");
> +  return populateLi(newLi, fullName, email, message);
> +}
> +
> +function populateLi(liNode, fullName, email, message) {
> +  liNode.innerHTML = formLiText(fullName, email, message);
> +
> +  liNode.appendChild(createEditButton());
> +  liNode.appendChild(createRemoveButton());
> +
> +  return liNode;
> +}
> +
>
> same here!
> ------------------------------
>
> In Final-Project/js/index.js
> <https://github.com/CodergirlVS/intro-to-programming-eclipse/pull/8#discussion_r661762242>
> :
>
> > +
> +  return liNode;
> +}
> +
> +messageForm.addEventListener("submit", (e) => {
> +  e.preventDefault();
> +  messageSection.style.display = "block";
> +  const fullName = e.target.user_name.value;
> +  const email = e.target.user_email.value;
> +  const message = e.target.user_message.value;
> +  console.log(fullName, email, message);
> +
> +  const newLi = createLi(fullName, email, message);
> +
> +  messageList.appendChild(newLi);
> +
>
> same here
> ------------------------------
>
> In Final-Project/index.html
> <https://github.com/CodergirlVS/intro-to-programming-eclipse/pull/8#discussion_r661764915>
> :
>
> > +                    <button type = "submit">Submit</button>
> +                </form>
> +            </section>
> +            <section id = 'messages'>
> +                <h2>Messages:</h2>
> +                    <ul>
> +                    </ul>
> +            </section>
> +            <section>
> +                <h2>Come Back!!</h2>
> +                <h3>Check this</h3>
> +                <video controls width = 500, height 500
> +                src = "http://treehouse-code-samples.s3.amazonaws.com/html-video-and-audio/bridge.mp4"
> +                type = "video/mp4">
> +                </video>
> +            </section>
>          <footer>
>              <!-- <small>&copy; 2021 Vaidehi's Portfolio</small>    -->
>
> It is better to have the header and footer the same color but it is
> totally up to your choose!
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/CodergirlVS/intro-to-programming-eclipse/pull/8#pullrequestreview-696548468>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATNB5JRCUFF7GPQPRUS5SH3TVNYLDANCNFSM46I2SEDA>
> .
>